parent=keycloak.v2

locales=en,zh-CN
styles=css/ysit-admin.css
logo=/img/brand-lockup.svg
favIcon=/img/brand-logo.png
favIconType=image/png
title=易识IT统一认证管理中心
description=易识IT统一认证与权限管理控制台
darkMode=true
kcDarkModeClass=pf-v5-theme-dark
contentHashPattern=(assets|avatar-admin)/.*
