parent=keycloak.v3

locales=en,zh-CN
styles=css/ysit-account.css css/avatar.css
logo=img/brand-lockup.svg
favIcon=/img/brand-logo.png
favIconType=image/png
title=易识IT账户中心
description=易识IT统一认证账户中心
darkMode=true
kcDarkModeClass=pf-v5-theme-dark
contentHashPattern=avatar-dist/assets/.*
